# docker pull registry.saas.hand-china.com/google_containers/kubernetes-dashboard-init-amd64:v1.0.0

# docker tag registry.saas.hand-china.com/google_containers/kubernetes-dashboard-init-amd64:v1.0.0 gcr.io/google_containers/kubernetes-dashboard-init-amd64:v1.0.0


# kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml


sudo: required
language: python

env:
  global:
    - DOCKER_REGISTRY_HOST=registry.saas.hand-china.com
    - DOCKER_USER=yunqiang.wu
    - DOCKER_PWD=Wu950429
    - DOCKER_FROM_PROJECT=gcr.io/google_containers
    - DOCKER_TO_PROJECT=registry.saas.hand-china.com/google_containers2
    - COPY_IMAGES=kube-addon-manager:v6.4-beta.2,kubernetes-dashboard-amd64:v1.8.0,pause-amd64:3.0,kube-addon-manager
    # 

services:
  - docker



before_install:
  - docker login $DOCKER_REGISTRY_HOST -u $DOCKER_USER -p $DOCKER_PWD
  - |
    if [[ x$COPY_IMAGES == x ]]; then 
      export COPY_IMAGES=mysql,redis
      echo "not set COPY_IMAGES envirmonent"
      exit 1
    fi

script:
  - OLD_IFS="$IFS"
  - IFS=","
  - COPY_IMAGES_TO_ARR=($COPY_IMAGES)
  - IFS="$OLD_IFS"
  # - s=kubernetes-dashboard-amd64:v1.8.0
  # - docker pull ${DOCKER_FROM_PROJECT}/${s}
  # - docker tag ${DOCKER_FROM_PROJECT}/${s} ${DOCKER_TO_PROJECT}/${s}
  # - docker push ${DOCKER_TO_PROJECT}/${s}



  - |
    for s in ${COPY_IMAGES_TO_ARR[@]}
    do
      docker pull ${DOCKER_FROM_PROJECT}/${s}
      docker tag ${DOCKER_FROM_PROJECT}/${s} ${DOCKER_TO_PROJECT}/${s}
      docker push ${DOCKER_TO_PROJECT}/${s}
      # sh -c "docker push ${DOCKER_TO_PROJECT}/${s}"
      echo docker push ${DOCKER_TO_PROJECT}/${s}  from   ${DOCKER_FROM_PROJECT}/${s}
    done
  - docker images -a

